theme: jekyll-theme-leap-day
title: DICKS 2019

defaults:
  - scope:
      path: "<a>DICKS</a> — Data Intensive Computations for Knowledge-based Systems (PAGE IN PROGRESS!)"
    values:
      title: "<a>DICKS</a> — Data Intensive Computations for Knowledge-based Systems (PAGE IN PROGRESS!)"
      description: "The First Annual Conference on Data Intensive Computations for Knowledge-based Systems (DICKS) is a deep learning and computational neuroscience conference that includes invited talks, demonstrations, symposia and oral and poster presentations of refereed papers. Following the conference, there are workshops which provide a less formal setting"

